version: '3.8'

services:
  
  backend:
    build:
      context: ./lmsbackend/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./lmsbackend/backend/.env
    restart: always

volumes:
  mongo-data:
