name: LMS CI/CD Pipeline

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 🧱 Frontend Build
    - name: Install & Build Angular Frontend
      working-directory: ./lmsfrontend/frontend
      run: |
        npm install
        npm run build --configuration production

    # ⚙️ Backend Build
    - name: Install & Build Node Backend
      working-directory: ./lmsbackend/backend
      run: |
        npm install
        npm run build

    # 🚀 Deploy to GCP via SSH
    - name: Deploy via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: |
          lmsfrontend/frontend/dist/
          lmsbackend/backend/dist/
        target: /home/${{ secrets.SSH_USER }}/lms-temp

    - name: SSH into GCP and move files
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Move frontend to /var/www/html/browser
          sudo rm -rf /var/www/html/browser
          sudo mv ~/lms-temp/lmsfrontend/frontend/dist /var/www/html/browser

          # Move backend to pm2 app location
          pm2 stop lms-backend
          sudo rm -rf ~/lms-backend/dist
          sudo mv ~/lms-temp/lmsbackend/backend/dist ~/lms-backend/dist
          pm2 start lms-backend
